#JWT details
app.jwtSecret = ${JWT_SECRET}
app.jwtExpirationMs = 540000

#DB Config
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/popcorntime
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

#ENABLE SWAGGER
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

#RazorPay details
api.razorpay.key.id = ${RAZORPAY_KEY_ID}
api.razorpay.key.secret = ${RAZORPAY_KEY_SECRET}

#REDIS details
redis.host = localhost
redis.port = 6379
redis.key.expiryTimeInMinutes = 6

#SPRING CACHE CONFIG : REDIS
spring.cache.type: redis
spring.cache.redis.time-to-live: 3600000

#RabbitMQ config
spring.rabbitmq.host: localhost
spring.rabbitmq.port: 5672
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

#rabbitMQ email-service properties
rabbitmq.email.queue.name = email_queue
rabbitmq.email.exchange.name = email_exchange
rabbitmq.email.binding.key = ticket.confirm.email
rabbitmq.email.routing.key = ticket.confirm.email

#rabbitMQ payment-fail-service properties
rabbitmq.payment.details.unsaved.queue.name = unsaved_payment_details_queue
rabbitmq.payment.details.unsaved.exchange.name = unsaved_payment_details_exchange
rabbitmq.payment.details.unsaved.binding.key = payment_details.unsaved
rabbitmq.payment.details.unsaved.routing.key = payment_details.unsaved
